# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 228ad4db61e9a58d22867a712074aa422effbcd4d4455acb63706280e9eea5e8599263d7e61c34ac08d89350a650d75010d99ada22152f5e2c01342aa6cb13af

test:
  secret_key_base: 38b16a146260d73514ea5d7cc0faf17b9ef9c5b6d621771bfe53c4b54ac4c3ff14549641bfb2502d35550fc22498eeb2f86fe31684b575c9b472502e69ac3ae3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
